version: '2.1'
services:  
  tumusica-api:
    build: .
    environment:
      SHOW_URLS: 'true'
      LISTS_URL: '34.66.226.238'
      LISTS_PORT: '4000'
      LISTS_ENTRY: '/'
      WSINTERFACE_URL: '34.66.226.238'
      WSINTERFACE_PORT: '4500'
      WSINTERFACE_ENTRY: '/'
      PLAY_URL: '34.66.226.238'
      PLAY_PORT: '3004'
      PLAY_ENTRY: '/api'
      USERS_URL: '34.66.226.238' 
      USERS_PORT: '3001'
      USERS_ENTRY: 'api/v1'
      UPLOAD_URL: '34.66.226.238'
      UPLOAD_PORT: '3002'
      UPLOAD_ENTRY: ''
      PATH_URL: '34.66.226.238'
      PATH_PORT: '3003'
      PATH_ENTRY: ''
      EXPO_NOTIFICATION: "https://exp.host/--/api/v2/push/send"
      WEB_NOTIFICATION: "https://fcm.googleapis.com/fcm/send"
      PORT: '5000'
    ports:
      - '5000:5000'