version: '2.1'
services:
  tumusica-api:
    build: .
    environment:
      SHOW_URLS: 'true'
      LISTS_URL: '192.168.1.72'
      LISTS_PORT: '4000'
      LISTS_ENTRY: '/'
      PLAY_URL: '192.168.1.72'
      PLAY_PORT: '3004'
      PLAY_ENTRY: '/api'
      #USERS_URL: '192.168.99.102' local
      USERS_URL: '192.168.1.72' 
      USERS_PORT: '3001'
      USERS_ENTRY: 'api/v1'
      UPLOAD_URL: '192.168.1.72'
      UPLOAD_PORT: '3002'
      UPLOAD_ENTRY: ''
    ports:
      - '5000:5000'
  