version: '2.1'
services:
  tumusica-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      COURSES_URL: '192.168.99.101'
      COURSES_PORT: '4000'
      COURSES_ENTRY: 'courses-ms/resources/courses'
      LISTS_URL: '192.168.99.101'
      LISTS_PORT: '4000'
      LISTS_ENTRY: '/'
    ports:
      - '5000:5000'
  